		<div id="footer" class="container_20">
			<div class="grid_10">
				Copyright &copy; Gentics Software GmbH. All rights reserved.
			</div>
			<div class="grid_10 text-right">
				<div class="float-right">
					<ul class="service-nav">
						<li><a href="/contact.php" title="contact">contact</a></li>
						<li><a href="/terms.php" title="terms">terms</a></li>
						<li><a href="/privacy.php" title="privacy">privacy</a></li>
					</ul>
				</div>
				<div>
				powered by <a target="_blank" href="http://www.gentics.com"><img id="genticslogo" src="/images/gentics-logo.png" alt="Gentics Software GmbH" title="Gentics Software GmbH"/></a>
				</div>
			</div>

			<div class="clear"></div>
		</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17460389-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

