		<div id="footer" class="container_20">
			<div class="grid_10">
				Copyright &copy; Gentics Software GmbH. All rights reserved.
			</div>
			<div class="grid_10 text-right">
				<div class="float-right">
					<ul class="service-nav">
						<li><a href="/contact.php" title="contact">contact</a></li>
						<li><a href="/terms.php" title="terms">terms</a></li>
						<li><a href="/privacy.php" title="privacy">privacy</a></li>
					</ul>
				</div>
				<div>
				powered by <a target="_blank" href="http://www.gentics.com"><img id="genticslogo" src="/images/gentics-logo.png" alt="Gentics Software GmbH" title="Gentics Software GmbH"/></a>
				</div>
			</div>

			<div class="clear"></div>
			<a href="https://github.com/alohaeditor/Aloha-Editor/" target="_blank"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/71eeaab9d563c2b3c590319b398dd35683265e85/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub"></a>
		</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17460389-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

