		<div id="header" class="container_20">
			<div class="grid_13">
				<div class="logo">
					<a id="logo" href="/index.php" title="Home"><img src="/images/aloha-editor-logo.png" alt="Home" /></a>
				</div>
				<ul class="topnav">
					<li><a href="/features.php" title="A shortcut for Aloha Editor features" class="new">Features</a></li>
					<li><a href="/about.php" title="Why Aloha? Why HTML5? Lern more about Aloha Editor">About</a></li>
					<li><a href="/demos.php" title="Feel the Aloha">Try it</a></li>
					<li><a href="/guides" title="Aloha Editor Guides">Guides</a></li>
					<li><a href="https://github.com/alohaeditor/Aloha-Editor/wiki" title="Aloha Wiki :)">Wiki</a></li>
				</ul>
			</div>
			<div class="grid_7">
				<ul class="topnav" style="float:right">
					<li><a href="http://getsatisfaction.com/aloha_editor" title="Get help or help others">Forum</a></li>
					<li><a href="https://github.com/alohaeditor/Aloha-Editor/issues" title="Our issue tracker">Issues</a></li>
					<!-- li><a href="/api" title="a must for developers">API</a></li -->
				</ul>
			</div>
			<div class="clear"></div>
		</div>
