
		<div id="header" class="container_20">
			<div class="grid_14">
				<div class="logo">
					<a id="logo" href="/index.php" title="Home"><img src="/logo/Aloha%20Editor%20logo%20text%20256.png" alt="Home" /></a>
				</div>
				<ul class="topnav">
					<li><a href="/about.php" title="Why Aloha Editor? Why HTML5? Lern more about Aloha Editor Experience.">About</a></li>
					<li><a href="/features.php" title="A shortcut for Aloha Editor features.">Features</a></li>
					<li><a href="/demos.php" title="Feel the Aloha Editor!">Demos</a></li>
					<li><a href="/guides" title="Aloha Editor Guides for User and Developer">Guides</a></li>
				</ul>
			</div>
			<div class="grid_6">
				<ul class="topnav" style="float:right">
					<li><a href="/blog/" title="Aloha Editor Blog">Blog</a></li>
					<li><a href="https://github.com/alohaeditor/Aloha-Editor/wiki" title="Aloha Editor Developer Wiki :)">Wiki</a></li>
					<li><a href="https://github.com/alohaeditor/Aloha-Editor/issues" title="Our issue tracker">Issue</a></li>
					<!-- li><a href="http://getsatisfaction.com/aloha_editor" title="Get help or help others">Forum</a></li>
					<li><a href="https://github.com/alohaeditor/Aloha-Editor/issues" title="Our issue tracker">Issues</a></li -->
					<!-- li><a href="/api" title="a must for developers">API</a></li -->
				</ul>
			</div>
			<div class="clear"></div>
		</div>
