<h3>Aloha Editor Core Developer</h3>
<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("h.meran@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://twitter.com/draftkraft">Haymo Meran</a><br />
<img src="<?=$path?>images/octocat.png" /> draftkraft<br />
<img alt="" src="<?=$path?>flags/it.gif" style="padding-right:5px" />Italy (South Tirol)
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("c.prerovsky@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://twitter.com/#!/blacktarmac">Clemens Prerovsky</a><br />
<img src="<?=$path?>images/octocat.png" /> cprerovsky<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("n.pomaroli@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://gentics.com">Norbert Pomaroli</a><br />
<img src="<?=$path?>images/octocat.png" /> npomaroli<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("p.salema@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://petrosalema.com/">Petro Salema</a><br />
<img src="<?=$path?>images/octocat.png" /> petro065<br />
<img alt="" src="<?=$path?>flags/tz.gif" style="padding-right:5px" />Tanzania
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("sufigari@googlemail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://stackoverflow.com/users/36862/inshallah">Tobias Steiner</a><br />
<img src="<?=$path?>images/octocat.png" /> deliminator<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("j.schueth@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://www.jotschi.de/">Johannes Sch&uuml;th</a><br />
<img src="<?=$path?>images/octocat.png" /> Jotschi<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("rene.kapusta@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://twitter.com/rene_kapusta" >Rene Kapusta</a><br />
<img src="<?=$path?>images/octocat.png" /> evo42<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>


<h3>Aloha Editor Contributor</h3>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("nkarageuzian@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://nka.re/">Nicolas Karageuzian</a><br />
<img src="<?=$path?>images/octocat.png" /> nka11<br />
<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("work@wimleers.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/wimleers">Wim Leers</a><br />
<img src="<?=$path?>images/octocat.png" /> wimleers<br />
<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("aurelien.manca@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://plop-cms.com">Aurelien Manca</a><br />
<img src="<?=$path?>images/octocat.png" /> noreiller<br />
<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("lakshan@web2media.net")));?>.jpg" style="float:left; padding:5px" />
<a href="http://laktek.com/">Lakshan Perera</a><br />
<img src="<?=$path?>images/octocat.png" /> laktek<br />
<img alt="" src="<?=$path?>flags/sri.gif" style="padding-right:5px" />Sri Lanka
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("supnig@constantinopel.at")));?>.jpg" style="float:left; padding:5px" />
<a href="http://www.supnig.com">Christopher Supnig</a><br />
<img src="<?=$path?>images/octocat.png" /> csupnig<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("joern.zaefferer@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://jqueryui.com">J&ouml;rn Zaefferer</a><br />
<img src="<?=$path?>images/octocat.png" /> jzaefferer<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("jerzy.kozera@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/jkozera">Jerzy Kozera</a><br />
<img src="<?=$path?>images/octocat.png" /> jkozera<br />
<img alt="" src="<?=$path?>flags/pl.gif" style="padding-right:5px" />Poland
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("io@sifu.io")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/sifu">Siegmund Führinger</a><br />
<img src="<?=$path?>images/octocat.png" /> sifu<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("david.de.rosier@jsgeeks.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/ddrcode">David de Rosier</a><br />
<img src="<?=$path?>images/octocat.png" /> ddrcode<br />
<img alt="" src="<?=$path?>flags/uk.gif" style="padding-right:5px" />United Kingdom
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("theodore@biadala.net")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/theodorab">Théodore Biadala</a><br />
<img src="<?=$path?>images/octocat.png" /> theodorab<br />
<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("fb@42dev.eu")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/florianbeer">Florian Beer</a><br />
<img src="<?=$path?>images/octocat.png" /> florianbeer<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("isburger@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/izak">Izak Burger</a><br />
<img src="<?=$path?>images/octocat.png" /> izak<br />
<img alt="" src="<?=$path?>flags/za.gif" style="padding-right:5px" />South Africa
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("rdworth@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://jqueryui.com">Richard D. Worth</a><br />
<img src="<?=$path?>images/octocat.png" /> rdworth<br />
<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("romain@reaklab.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://www.wikeo.be">Romain Carliere</a><br />
<img src="<?=$path?>images/octocat.png" /> romaincarlier<br />
<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("henri.bergius@iki.fi")));?>.jpg" style="float:left; padding:5px" />
<a href="http://bergie.iki.fi">Henri Bergius</a><br />
<img src="<?=$path?>images/octocat.png" /> bergie<br />
<img alt="" src="<?=$path?>flags/fi.gif" style="padding-right:5px" />Finnland
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("scott.gonzalez@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://jqueryui.com">Scott Gonzalez</a><br />
<img src="<?=$path?>images/octocat.png" /> scottgonzalez<br />
<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mail@nils-dehl.de")));?>.jpg" style="float:left; padding:5px" />
<a href="http://www.nils-dehl.de">Nils Dehl</a><br />
<img src="<?=$path?>images/octocat.png" /> mrsunshine<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("hlubek@networkteam.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://networkteam.com">Christopher Hlubek</a><br />
<img src="<?=$path?>images/octocat.png" /> chlu<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("jensen@networkteam.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://twitter.com/berit_jensen">Berit Jensen</a><br />
<img src="<?=$path?>images/octocat.png" /> bjen<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("sebastian@typo3.org")));?>.jpg" style="float:left; padding:5px" />
<a href="http://sandstorm-media.de">Sebastian Kurf&uuml;rst</a><br />
<img src="<?=$path?>images/octocat.png" /> skurfuerst<br />
<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("edtsech@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://github.com/edtsech">Eduard Tsech</a><br />
<img src="<?=$path?>images/octocat.png" /> edtsech<br />
<img alt="" src="<?=$path?>flags/ru.gif" style="padding-right:5px" />Russia
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/e1b92304c583f1f746c3e85f389a8b81.png" style="float:left; padding:5px" />
<a href="http://github.com/bistory">Thomas L&eacute;t&eacute;</a><br />
<img src="<?=$path?>images/octocat.png" /> bistory<br />
<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("scherrer@livenet.ch")));?>.jpg" style="float:left; padding:5px" />
<a href="http://github.com/chuengu">Daniel Scherrer</a><br />
<img src="<?=$path?>images/octocat.png" /> chuengu<br />
<img alt="" src="<?=$path?>flags/ch.gif" style="padding-right:5px" />Switzerland
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("contact@balupton.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://www.balupton.com">Benjamin Lupton</a><br />
<img src="<?=$path?>images/octocat.png" /> balupton<br />
<img alt="" src="<?=$path?>flags/au.gif" style="padding-right:5px" />Australia
</p>

<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mike@appendto.com")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://mike-hostetler.com/">Mike Hostetler</a><br />
	<img src="<?=$path?>images/octocat.png" /> mikehostetler<br />
	<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("iturgeon@gmail.com")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://ianturgeon.com">Ian Turgeon</a><br />
	<img src="<?=$path?>images/octocat.png" /> iturgeon<br />
	<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("ljean@apidev.fr")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://www.apidev.fr">Luc JEAN</a><br />
	<img src="<?=$path?>images/octocat.png" /> ljean<br />
	<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
</p>


<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("robert@tiki.org")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://visop-dev.com">Robert Plummer</a><br />
	<img src="<?=$path?>images/octocat.png" /> RobertLeePlummerJr<br />
	<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>


<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("rico.bl@gmail.com")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://ricobl.wordpress.com">Enrico Batista da Luz</a><br />
	<img src="<?=$path?>images/octocat.png" /> ricobl<br />
	<img alt="" src="<?=$path?>flags/br.gif" style="padding-right:5px" />Brazil
</p>


<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("hallock@gmail.com")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://thomashallock.com">Thomas Hallock</a><br />
	<img src="<?=$path?>images/octocat.png" /> antialias<br />
	<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("arosborough@acgnw.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/arosboro">Andrew Rosborough</a><br />
<img src="<?=$path?>images/octocat.png" /> arosboro<br />
<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("websafe@cjboco.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/cjboco">Doug Jones</a><br />
<img src="<?=$path?>images/octocat.png" /> cjboco<br />
<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("patrik.henningsson@gmail.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/pahen">Patrik Henningsson</a><br />
<img src="<?=$path?>images/octocat.png" /> pahen<br />
<img alt="" src="<?=$path?>flags/se.gif" style="padding-right:5px" />Sweden
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("lroggendorff@myemma.com")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/lroggendorff">Lance Roggendorff</a><br />
<img src="<?=$path?>images/octocat.png" /> lroggendorff<br />
<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("eric@ericschrijver.nl")));?>.jpg" style="float:left; padding:5px" />
<a href="https://github.com/codingisacopingstrategy">Eric Schrijver</a><br />
<img src="<?=$path?>images/octocat.png" /> codingisacopingstrategy<br />
<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
</p>



<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mike.bauer@hatdiebesteagentur.at")));?>.jpg" style="float:left; padding:5px" />
<a href="http://getdesigned.at">Matthias Redl</a><br />
Cook<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("a.szlezak@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://gentics.com">Alexander Szlezak</a><br />
Community Angel<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("m.aghamanoukjan@gentics.com")));?>.jpg" style="float:left; padding:5px" />
<a href="http://gentics.com">Manuel Aghamanoukjan</a><br />
Community Angel<br />
<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>

<p style="clear:both">
	<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("h.haas@gentics.com")));?>.jpg" style="float:left; padding:5px" />
	<a href="http://www.darky.at/">Harald Haas</a><br />
	Community Angel<br />
	<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
</p>


<h3>Thanks to</h3>
<p><a href="http://drewwilson.com">Drew Wilson</a><br/>
jQuery autosuggest (collaboration)</p>
<p><a href="http://www.jenitennison.com">Jeni Tennison</a><br />
rdfQuery (collaboration)</p>
<p><a href="http://www.kmsm.ca">Joshua Kelly</a><br />
moby dick (contribution)</p>
<p><a href="http://www.zachstronaut.com">Zachary Johnson</a><br />
magic cube (contribution)</p>
<p><a href="http://123information.wordpress.com">Isabella Mader</a><br />
Wikipedia (community angel)</p>
<p><a href="http://www.kimberlygeswein.com">Kimberly Geswein</a><br />
Indie Font (contribution)</p>
