				<h3>Aloha Editor Core Developer</h3>
				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("h.meran@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://twitter.com/draftkraft">Haymo Meran</a><br />
				Project leader<br />
				<img alt="" src="<?=$path?>flags/it.gif" style="padding-right:5px" />Italy (South Tirol)
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("c.prerovsky@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://twitter.com/#!/blacktarmac">Clemens Prerovsky</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("nkarageuzian@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://nka.re/">Nicolas Karageuzian</a><br />
				Javascript Wizard<br />
				<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("n.pomaroli@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://gentics.com">Norbert Pomaroli</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("p.salema@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://petrosalema.com/">Petro Salema</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/tz.gif" style="padding-right:5px" />Tanzania
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("sufigari@googlemail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://stackoverflow.com/users/36862/inshallah">Tobias Steiner</a><br />
				Javascript 忍者<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("j.schueth@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://www.jotschi.de/">Johannes Sch&uuml;th</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("rene.kapusta@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://twitter.com/rene_kapusta" >Rene Kapusta</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<h3>Aloha Editor Contributor</h3>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("work@wimleers.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/wimleers">Wim Leers</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("aurelien.manca@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://plop-cms.com">Aurelien Manca</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("lakshan@web2media.net")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://laktek.com/">Lakshan Perera</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/sri.gif" style="padding-right:5px" />Sri Lanka
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("supnig@constantinopel.at")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://www.supnig.com">Christopher Supnig</a><br />
				Webdeveloper<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("joern.zaefferer@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://jqueryui.com">J&ouml;rn Zaefferer</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("jerzy.kozera@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/jkozera">Jerzy Kozera</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/pl.gif" style="padding-right:5px" />Poland
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("io@sifu.io")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/sifu">Siegmund Führinger</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("david.de.rosier@jsgeeks.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/ddrcode">David de Rosier</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/uk.gif" style="padding-right:5px" />United Kingdom
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("theodore@biadala.net")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/theodorab">Théodore Biadala</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/fr.gif" style="padding-right:5px" />France
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("fb@42dev.eu")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/florianbeer">Florian Beer</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("isburger@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="https://github.com/izak">Izak Burger</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/za.gif" style="padding-right:5px" />South Africa
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("rdworth@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://jqueryui.com">Richard D. Worth</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("romain@reaklab.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://www.wikeo.be">Romain Carliere</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("henri.bergius@iki.fi")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://bergie.iki.fi">Henri Bergius</a><br />
				CoffeeScript Guru<br />
				<img alt="" src="<?=$path?>flags/fi.gif" style="padding-right:5px" />Finnland
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("scott.gonzalez@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://jqueryui.com">Scott Gonzalez</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mail@nils-dehl.de")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://www.nils-dehl.de">Nils Dehl</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("hlubek@networkteam.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://networkteam.com">Christopher Hlubek</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("jensen@networkteam.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://twitter.com/berit_jensen">Berit Jensen</a><br />
				Webdesigner<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("sebastian@typo3.org")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://sandstorm-media.de">Sebastian Kurf&uuml;rst</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/de.gif" style="padding-right:5px" />Germany
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("edtsech@gmail.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="">Eduard Tsech</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/ru.gif" style="padding-right:5px" />Russia
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/e1b92304c583f1f746c3e85f389a8b81.png" style="float:left; padding:5px" />
				Thomas L&eacute;t&eacute;<br />
				Speed and optimisations Guru.<br />
				<img alt="" src="<?=$path?>flags/be.gif" style="padding-right:5px" />Belgium
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("scherrer@livenet.ch")));?>.jpg" style="float:left; padding:5px" />
				<a href="">Daniel Scherrer</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/ch.gif" style="padding-right:5px" />Switzerland
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("contact@balupton.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://www.balupton.com">Benjamin Lupton</a><br />
				Javascript Guru<br />
				<img alt="" src="<?=$path?>flags/au.gif" style="padding-right:5px" />Australia
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mike.bauer@hatdiebesteagentur.at")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://getdesigned.at">Matthias Redl</a><br />
				Cook<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("a.szlezak@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://gentics.com">Alexander Szlezak</a><br />
				Community Angel<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
				<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("m.aghamanoukjan@gentics.com")));?>.jpg" style="float:left; padding:5px" />
				<a href="http://gentics.com">Manuel Aghamanoukjan</a><br />
				Community Angel<br />
				<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>
				
				<p style="clear:both">
					<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("h.haas@gentics.com")));?>.jpg" style="float:left; padding:5px" />
					<a href="http://www.darky.at/">Harald Haas</a><br />
					Community Angel<br />
					<img alt="" src="<?=$path?>flags/at.gif" style="padding-right:5px" />Austria
				</p>

				<p style="clear:both">
					<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("mike@appendto.com")));?>.jpg" style="float:left; padding:5px" />
					<a href="http://mike-hostetler.com/">Mike Hostetler</a><br />
					Javascript Guru<br />
					<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
				</p>


				<p style="clear:both">
					<img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim("iturgeon@gmail.com")));?>.jpg" style="float:left; padding:5px" />
					<a href="http://ianturgeon.com">Ian Turgeon</a><br />
					Web developer<br />
					<img alt="" src="<?=$path?>flags/us.gif" style="padding-right:5px" />USA
				</p>

				<h3>Thanks to</h3>
				<p><a href="http://drewwilson.com">Drew Wilson</a><br/>
				jQuery autosuggest (collaboration)</p>
				<p><a href="http://www.jenitennison.com">Jeni Tennison</a><br />
				rdfQuery (collaboration)</p>
				<p><a href="http://www.kmsm.ca">Joshua Kelly</a><br />
				moby dick (contribution)</p>
				<p><a href="http://www.zachstronaut.com">Zachary Johnson</a><br />
				magic cube (contribution)</p>
				<p><a href="http://123information.wordpress.com">Isabella Mader</a><br />
				Wikipedia (community angel)</p>
				<p><a href="http://www.kimberlygeswein.com">Kimberly Geswein</a><br />
				Indie Font (contribution)</p>
