<? 
$lang['en'] = "English";
$lang['ar'] = "Arabic";
$lang['bn'] = "Bengali";
$lang['pt-br'] = "Brazilian";
$lang['bg'] = "Bulgarian"; $lang['l.bg'] = "Български";
$lang['zh'] = "Chinese";
$lang['cz'] = "Czech";
$lang['da'] = "Danish";
$lang['nl'] = "Dutch";
$lang['fi'] = "Finnish";
$lang['es'] = "Esperanto";
$lang['et'] = "Estonian";
$lang['fr'] = "French";
$lang['gl'] = "Galician";
$lang['de'] = "German";
$lang['hi'] = "Hindi";
$lang['it'] = "Italian";
$lang['jp'] = "Japanese";
$lang['ko'] = "Korean";
$lang['pl'] = "Polish";
$lang['pt'] = "Portuguese";
$lang['ro'] = "Romanian";
$lang['ru'] = "Russian";
$lang['sr'] = "Serbian";
$lang['es'] = "Spanish";
$lang['sv'] = "Swedish";
$lang['sw'] = "Swahili";
$lang['tl'] = "Tagalog";
$lang['tr'] = "Turkish";


/*
$user[] = Array('name'=>'Haymo Meran','email'=>'h.meran@gentics.com','langs'=>Array('de','it'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Benjamin "balupton" Lupton','email'=>'contact@balupton.com','langs'=>Array('en'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'nkarageuzian','email'=>'nkarageuzian@gmail.com','langs'=>Array('fr'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'n.pomaroli','email'=>'n.pomaroli@gentics.com','langs'=>Array('de'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'c.prerovsky','email'=>'c.prerovsky@gentics.com','langs'=>Array('de'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'rene.kapusta','email'=>'rene.kapusta@gmail.com','langs'=>Array('de'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'thomas','email'=>'thomas@reaklab.com','langs'=>Array('fr'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'km.schremser','email'=>'km.schremser@gentics.com','langs'=>Array('de'),'lname'=>'','link'=>'');
*/
$user[] = Array('name'=>'Alfredo Engenharia','email'=>'alfredo@aatecnologia.com.br','langs'=>Array('pt-br'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Christian Oliveir Alofonso','email'=>'christianoliveirausal@gmail.com','langs'=>Array('gl'),'flags'=>Array('es'),'lname'=>'','link'=>'http://www.christianoliveira.com');
$user[] = Array('name'=>'ntf','email'=>'ntf@live.hk','langs'=>Array('zh'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'defite','email'=>'defite@gmail.com','langs'=>Array('ru'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Mohamed Racem Zouaghi','email'=>'racem@ebtekarmedia.com','langs'=>Array('ar'),'lname'=>'','link'=>'http://www.ebtekarmedia.com');
$user[] = Array('name'=>'info','email'=>'info@bruinsmareclame.com','langs'=>Array('nl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Soren Malling','email'=>'soren.malling@gmail.com','langs'=>Array('da'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'tadeusz','email'=>'tadeusz@lazurski.pl','langs'=>Array('pl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Petar Petrov','email'=>'pepetrov@gmail.com','langs'=>Array('bg'),'lname'=>'Петър Петров','link'=>'http://twitter.com/peshkira');
$user[] = Array('name'=>'Christopher Supnig','email'=>'supnig@constantinopel.at','langs'=>Array('de'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Helle Jensen','email'=>'helle@klean.dk','langs'=>Array('da'),'lname'=>'','link'=>'http://twitter.com/HelleJensen');
$user[] = Array('name'=>'Ondra Macoszek','email'=>'ondra.macoszek@gmail.com','langs'=>Array('cz'),'lname'=>'','link'=>'http://ondra.macoszek.cz');
$user[] = Array('name'=>'biodiscover','email'=>'biodiscover@gmail.com','langs'=>Array('tr'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'ana','email'=>'ana@constantinopel.at','langs'=>Array('sr'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'efrainyoel','email'=>'efrainyoel@gmail.com','langs'=>Array('es'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Petro Salema','email'=>'salemapetro@gentics.com','langs'=>Array('sw'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'vbert','email'=>'wsobczak@gmail.com','langs'=>Array('pl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Lincoln Sbrito','email'=>'lincoln.sbrito@gmail.com','langs'=>Array('pt'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'emiel','email'=>'emiel@salomonv.nl','langs'=>Array('nl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'rolando','email'=>'rolando@bandd.pe','langs'=>Array('es'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'davilima6','email'=>'davilima6@gmail.com','langs'=>Array('pt-br'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'André Loop','email'=>'am@nessus.at','langs'=>Array('ro','it','tl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Adam','email'=>'adam@kodamera.se','langs'=>Array('sv'),'flags'=>Array('se'),'lname'=>'','link'=>'http://twitter.com/henlfern');
$user[] = Array('name'=>'Krystian','email'=>'info@sinner.com.pl','langs'=>Array('pl'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Miguel Angelyanez','email'=>'miguelangelyanez@conecta6.com','langs'=>Array('es'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Antonio Azevedo','email'=>'tony.yesitsme@gmail.com','langs'=>Array('pt'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'Mario','email'=>'marioraudsepp@gmail.com','langs'=>Array('et'),'flags'=>Array('ee'),'lname'=>'','link'=>'');
$user[] = Array('name'=>'mert','email'=>'mert@merttorun.com','langs'=>Array('tr'),'flags'=>Array('tr'),'lname'=>'','link'=>'');
?>
		
				<h2>Do you speak <? echo $lang[array_rand($lang)]; ?>? We do.</h2>
				<br /><p>A lot of engaged people help translating the Aloha Editor in different languages. We thank all the supporters listed here and those not listed as well. 
				Join this international and multi cultural project team! No programming knowledge necessary to translate. 
				A machine translation functionality helps to get fast results.</p>
				<p><a href="http://mygengo.com/string/p/aloha-editor-1/access/request">I will translate.</a> 
				<i>Please add a message with the lanugage you will translate to when registering.<br /> 
				<a href="http://mygengo.com/string/p/aloha-editor-1/">Check translation state</a>.We will add not listed languages.</i> 
				</p>

				<h3>Translation heros</h3>
<? foreach ($user as $u) { ?>
				<p style="float:left;width:325px; overflow:hidden">
                                <img alt="" src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($u['email'])));?>.jpg" style="float:left; padding:5px" />
                                <?=$u['name']?> <? if ($u['lname']) echo "($u[lname])"; ?><br />
<? foreach ($u['langs'] as $k=>$l) { ?>
                                <img title='<?=$lang[$l]?>' src="<?=$path?>flags/<?=($u['flags'])?$u['flags'][$k]:$l?>.gif" style="padding-right:5px" /> <?=($lang['l.'.$l])?"<span title='".$lang[$l]."'>".$lang['l.'.$l]."</span>":$lang[$l]?>
<? } ?> 
                                <a href="<?=$u['link']?>"><?=substr($u['link'],7)?></a><br />
                                </p>
<? } ?>

